apps/topics/urls.py
# -*- coding=utf-8 -*-
__author__ = 'zhaojie'
__date__ = '2018/3/13 11:06'
from django.contrib import admin
from django.conf.urls import url, include
from .views import AskListView, AskAnswersView, PostView, AddAnswerView, AddReplyView
import xadmin


urlpatterns = [

    url('list/(?P<topic_id>.*)$', AskListView.as_view(), name='chushilist'),
    url('ask/(?P<ask_id>.*)$', AskAnswersView.as_view(), name='chushiask'),
    url('po/(?P<topic_id>.*)$',PostView.as_view(), name='post'),
    url('add_answer/(?P<ask_id>.*)$', AddAnswerView.as_view(), name='Add_answer'),
    url('add_reply/(?P<answer_id>.*)$', AddReplyView.as_view(), name='add_reply'),

]

apps/users/urls.py
# -*- coding=utf-8 -*-
__author__ = 'zhaojie'
__date__ = '2018/3/19 13:08'
from django.conf.urls import url, include
from .views import UserinfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, MyMessageView, ActiveUserView, ForgetPwdView, ModifyPwdView, ResetView
urlpatterns =[
    # 用户信息
    url(r'^info/$', UserinfoView.as_view(), name='user_info'),
    # 用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(), name='image_upload'),
    # 用户修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),
    # 发送邮箱验证码
    url(r'sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),
    # 修改邮箱
    url(r'^mymessage/$', MyMessageView.as_view(), name='mymessage'),



]

bbs/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from users.views import IndexView, RegisterView
import xadmin
from bbs.settings import MEDIA_ROOT
from django.views.static import serve
from topics.views import EditorView, PostView, uploadfiles_view
from users.views import LogoutView
from users.views import ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView
urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    url('admin/', admin.site.urls),
    url('^$', IndexView.as_view(), name='index'),
    url('^register/$', RegisterView.as_view(), name='register'),
    url('^captcha/', include('captcha.urls')),
    url('^topics/', include('topics.urls', namespace='topics'), ),
    url('^ed/', EditorView.as_view(), name='editor'),
    url('uploadfiles/', uploadfiles_view.as_view()),
    url('^logout/$', LogoutView.as_view(), name='logout'),  # 这里是方法，有括号
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    url('^forget/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name='reset_pwd'),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name='modify_pwd'),
]

apps/topics/models.py
# coding=utf-8
from django.db import models
from datetime import datetime
from users.models import UserProfile
# Create your models here.
class Topics(models.Model):
    name = models.CharField(max_length=30, default='话题', verbose_name='话题名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    topic_ask_nums = models.IntegerField( default=0, verbose_name='话题问答数量')

    class Meta:
        verbose_name = u'话题'
        verbose_name_plural  = verbose_name

    def __str__(self):
        return self.name

class Ask(models.Model):
    topics = models.ForeignKey(Topics, verbose_name='所属话题', null=True)
    user = models.ForeignKey(UserProfile, verbose_name='用户名' ,null=True)
    title = models.CharField(max_length=50, verbose_name='问题')
    detail = models.TextField(max_length=500, verbose_name='问题细节')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    tag = models.CharField(max_length=10, verbose_name='标签', default='经验总结')

    class Meta:
        verbose_name = u'问题'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class AskAnswers(models.Model):
    '问题回答'
    user = models.ForeignKey(UserProfile, verbose_name=u'用户名')
    ask = models.ForeignKey(Ask, verbose_name=u'问题', null=True)
    answer_title = models.CharField(max_length=200, verbose_name=u'回答')
    answer_detail = models.TextField(max_length=500, verbose_name='详细回答', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
       verbose_name = u'问题回答'
       verbose_name_plural = verbose_name
    def __str__(self):
        return self.answer_detail


class AnswersReply(models.Model):
    '课程评论'
    user = models.ForeignKey(UserProfile, verbose_name=u'用户名')
    ask = models.ForeignKey(Ask, verbose_name=u'课程', null=True)
    answer = models.ForeignKey(AskAnswers, verbose_name=u'回答', null=True)
    answer_reply = models.TextField(max_length=200, verbose_name='回复',default='', null=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
       verbose_name = u'回答回复'
       verbose_name_plural = verbose_name
    def __str__(self):
        return self.user.username


class Attachment(models.Model):
    """
    附件数据库，图片地址，文件地址和视频地址，在content内容里关联
    """
    img = models.ImageField(upload_to='img', default='')
    file = models.FileField(upload_to='file', default='')
    video = models.FileField(upload_to='video', default='')
    ctime = models.DateTimeField(auto_now_add=True)
    mtime = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = u'附件上传'
        verbose_name_plural = verbose_name

apps/topics/forms.py
# -*- coding=utf-8 -*-
__author__ = 'zhaojie'
__date__ = '2018/3/18 19:38'

apps/users/forms.py
# -*- coding=utf-8 -*-
__author__ = 'zhaojie'
__date__ = '2018/2/13 17:36'
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile
class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=3)


class RegisterForm(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=5)
    captcha = CaptchaField(error_messages={'invalid': u'验证码错误'})


class ForgetForm(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField(error_messages={'invalid': u'验证码错误'})


class ModifyPwdForm(forms.Form):
    password1 = forms.CharField(required=True, min_length=5)
    password2 = forms.CharField(required=True, min_length=5)


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nick_name', 'gender', 'birday', 'address', 'mobile']

apps/topics/views.py
from django.shortcuts import render
from django.views.generic.base import View
from .models import Topics, Ask, AskAnswers, AnswersReply, Attachment
from users.models import UserProfile
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
import json
from django.utils import timezone
# Create your views here.
class AskListView(View):
    def get(self, request, topic_id):
        topic = Topics.objects.get(id = topic_id)
        asks = Ask.objects.filter(topics=topic)
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(asks, 10, request=request)  # 数字 每页显示几个 不能少 否则会报错
        asks = p.page(page)
        return render(request, 'topiclist.html', {'topic': topic, 'asks': asks})


class AskAnswersView(View):
    def get(self, request, ask_id):

        ask = Ask.objects.get(id=ask_id)
        topic = ask.topics
        answers = AskAnswers.objects.filter(ask=ask)
        return render(request, 'ask.html', {'ask': ask, 'answers': answers,'topic': topic })


class EditorView(View):
    def get(self, request):
        return render(request, 'kedit.html',{})



class PostView(View):
    """
    提问题
    """
    def get(self, request, topic_id):
        topic = Topics.objects.get(id=topic_id)
        return render(request, 'post.html', {'topic': topic})
    def post(self, request, topic_id):
        if not request.user.is_authenticated():
            # 判断用户登录状态
            return HttpResponse('{"status":"fail", "msg":"用户未登录"}', content_type='application/json')
        topic = Topics.objects.get(id=topic_id)
        title = request.POST.get('title')
        detail = request.POST.get('content')
        ask = Ask()
        ask.topics = topic
        ask.user = request.user
        ask.title = title
        ask.detail = detail
        ask.add_time = timezone.now()
        ask.save()
        return HttpResponseRedirect(reverse('topics:chushilist',  kwargs={"topic_id": topic.id}))

class AddAnswerView(View):
    """
    回帖
    """
    def get(self, request, ask_id):
        ask = Ask.objects.get(id=ask_id)
        return render(request, 'post.html',{'ask': ask})
    def post(self, request, ask_id):
        if not request.user.is_authenticated():
            # 判断用户登录状态
            return HttpResponse('{"status":"fail", "msg":"用户未登录"}', content_type='application/json')
        ask = Ask.objects.get(id=ask_id)
        title = request.POST.get('title')
        detail = request.POST.get('content')
        answer = AskAnswers()
        answer.ask = ask
        answer.add_time = timezone.now()
        answer.user = request.user
        answer.answer_title = title
        answer.answer_detail = detail
        answer.save()
        return HttpResponseRedirect(reverse('topics:chushiask',  kwargs={"ask_id": ask.id}))

class AddReplyView(View):
    """
    回复
    """
    def get(self, request, answer_id):
        answer = AskAnswers.objects.get(id=answer_id)
        return render(request, 'post.html',{'answer': answer})
    def post(self, request, answer_id):
        if not request.user.is_authenticated():
            # 判断用户登录状态
            return HttpResponse('{"status":"fail", "msg":"用户未登录"}', content_type='application/json')
        answer = AskAnswers.objects.get(id=answer_id)
        title = request.POST.get('title')
        detail = request.POST.get('content')
        ask = answer.ask
        reply =AnswersReply()
        reply.answer = answer
        reply.user = request.user
        reply.add_time = timezone.now()
        reply.answer_reply = detail
        reply.save()
        return HttpResponseRedirect(reverse('topics:chushiask',  kwargs={"ask_id": ask.id}))





class uploadfiles_view(View):
    """
    附件上传
    """
    def get(self, request):
        return render(request, 'editor.html')

    def post(self, request):
        dirs = request.GET.get('dir')
        print(dirs)
        file = request.FILES.get('imgFile')
        uploadfiles = Attachment()
        if dirs == 'image':
            uploadfiles.img = file
            uploadfiles.save()
            print(uploadfiles.img.url)
            dict = {
                "error": 0,
                "url": uploadfiles.img.url
            }
        elif dirs == 'file':
            uploadfiles.file = file
            uploadfiles.save()
            print(uploadfiles.file.url)
            dict = {
                "error": 0,
                "url": uploadfiles.file.url
            }
        elif dirs == 'media':
            uploadfiles.video = file
            uploadfiles.save()
            print(uploadfiles.video.url)
            dict = {
                "error": 0,
                "url": uploadfiles.video.url
            }

        return HttpResponse(json.dumps(dict))

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> 链接无效 </p>
</body>
</html>

templates/kedit.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<textarea id="editor_id" name="content" style="height: 400px" >请输入评论</textarea>

<script src="{% static 'js/editor/kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'js/editor/kindeditor/lang/zh-CN.js' %}"></script>
    <script src="{% static 'js/editor/kindeditor/themes/default/default.css' %}"></script>
    <script>
        KindEditor.ready(function (k) {
            window.editor = k.create('#editor_id',{
                resizeType:1,
                allowPreviewEmoticons : false,
                allowImageRemote : false,
                {#处理url#}
                uploadJson : '/upload/kindeditor',

            });
        })


    </script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>考研论坛注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>
<div class="loginbox dialogbox">
    <h1>账号登录</h1>
    <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
    <div class="cont">
        <form id="jsLoginForm" autocomplete="off">
            <div class="box">
                <span class="word3">用户名</span>
                <input type="text" name="account_l" id="account_l" placeholder="手机号/邮箱" />
            </div>
            <div class="box">
                <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
                <input type="password" name="password_l" id="password_l" placeholder="请输入您的密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips"></div> <!--登录错误提示-->
            <div class="btns">
                <span><input type="checkbox" id="jsAutoLogin" />&nbsp;自动登录</span>
                <span class="forget btn fr">忘记密码</span>
            </div>
            <div class="button">
                <input type="button" value="登录" id="jsLoginBtn" />
            </div>
            <div class="btns">
                <span class="fr">没有账号？<span class="regist btn">立即注册</span></span>
            </div>
        </form>
    </div>
</div>
<div class="dialog" id="jsDialog">
    <!--提示弹出框-->
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <div  class="noactivebox dialogbox" id="jsUnactiveForm" >
        <h1>邮件验证提示</h1>
        <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
        <div class="center">
            <img src="{% static 'images/send.png' %}"/>
            <p>我们已经向您的邮箱<span class="green" id="jsEmailToActive">12@13.com</span>发送了邮件，<br/>为保证您的账号安全，请及时验证邮箱</p>
            <p class="a"><a class="btn" id="jsGoToEmail" target="_blank" href="http://mail.qq.com">去邮箱验证</a></p>
            <p class="zy_success upmove"></p>
            <p style="display: none;" class="sendE2">没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件（<span class="c5c">60s</span>）</p>
            <p class="sendE">没收到，您可以查看您的垃圾邮件和被过滤邮件，<br/>也可以<span class="c5c green" id="jsSenEmailAgin" style="cursor: pointer;">再次发送验证邮件</span></p>
        </div>
    </div>
</div>

<div class="bg" id="dialogBg"></div>

<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <!--<h2 class="active">手机注册</h2>-->
                    <h2>邮箱注册</h2>
                </div>
                <!--<div class="tab-form">-->
                    <!--<form id="mobile_register_form" autocomplete="off">-->
                        <!--<input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />-->
                        <!--<div class="form-group marb20">-->
                            <!--<label>手&nbsp;机&nbsp;号</label>-->
                            <!--<input id="jsRegMobile" name="account" type="text" placeholder="请输入您的手机号码" />-->
                        <!--</div>-->
                        <!--<div class="form-group marb20" id="jsRefreshCode">-->
                            <!--<label>验&nbsp;证&nbsp;码</label>-->
                            <!--<input autocomplete="off" class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_1" name="captcha_m_1" placeholder="请输入验证码" type="text" /> <input class="form-control-captcha mobile-register-captcha" id="mobile-register-captcha_0" name="captcha_m_0" placeholder="请输入验证码" type="hidden" value="29953bacf7005e8469388b449d97d00d523c1706" /> &nbsp;<img src="/captcha/image/29953bacf7005e8469388b449d97d00d523c1706/" alt="captcha" class="captcha" />-->
                        <!--</div>-->
                        <!--<div class="clearfix">-->
                            <!--<div class="form-group marb8 verify-code">-->
                                <!--<label>短信验证码</label>-->
                                <!--<input id="jsPhoneRegCaptcha" name="mobile_code" type="text" placeholder="输入手机验证码" />-->
                            <!--</div>-->
                            <!--<input class="verify-code-btn sendcode" id="jsSendCode" value="发送验证码">-->
                        <!--</div>-->
                        <!--<div class="form-group marb8">-->
                            <!--<label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>-->
                            <!--<input id="jsPhoneRegPwd" name="password_m" type="password" placeholder="请输入6-20位非中文字符密码" />-->
                        <!--</div>-->
                        <!--<div class="error btns" id="jsMobileTips"></div>-->
                        <!--<div class="auto-box marb8">-->

                        <!--</div>-->
                        <!--<input class="btn btn-green" id="jsMobileRegBtn" type="button" value="注册并登录" />-->
                    <!--</form>-->
                <!--</div>-->
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'register' %}" autocomplete="off">
                        <input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />
                        <div class="form-group marb20 {% if register_form.errors.email %}errorput{% endif %}">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="{{ register_form.email.value }}" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.password %}errorput{% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="{{ register_form.password.value }}" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 {% if register_form.errors.captcha %}errorput{% endif %}">
                            <label>验&nbsp;证&nbsp;码</label>
                            {{ register_form.captcha }}
                        </div>
                        <div class="error btns" id="jsEmailTips">{% for key,error in register_form.errors.items %}{{ error }}{% endfor %}{{ msg }}</div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                    <input type='hidden' name='csrfmiddlewaretoken' value='5I2SlleZJOMUX9QbwYLUIAOshdrdpRcy' />
                    {% csrf_token %}
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="{% url 'index' %}">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static  'js/unslider.js'%}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/send_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p> 邮件已发送，请查收 </p>
</body>
</html>

templates/usercenter-info.html
{% extends 'usercenter-base.html' %}
{% block title %}杰信在线教育{% endblock %}
{% block custom_bread %}
        <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>个人信息</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block right_content %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:image_upload' %}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                        <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                        {% csrf_token %}
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birday" value="{{ request.user.birday }}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male" {% if request.user.gender == 'male' %}checked="checked"{% endif %}>男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female"  {% if request.user.gender == 'female' %}checked="checked"{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address }}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile|default_if_none:'' }}" maxlength="10">

                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email }}"/>
                            <span class="green changeemai_btn">[修改]</span>
                    	</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
						</li>
					</ul>
                    <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                {% csrf_token %}
				</form>
			</div>
		</div>
	</div>
{% endblock %}

templates/usercenter-message.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}

{% block custom_bread %}
        <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的消息</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的消息</h1>
			</div>

		</div>
		<div class="personal_des permessage">
			<div class="head">
				<ul class="tab_header messagehead">
					<li class="active"><a href="{% url 'users:mymessage' %}">个人消息</a> </li>
				</ul>


			</div>
			<div class="messagelist">
                    {% for message in messages.object_list %}
                    <div class="messages">
                        <div class="fr">
                            <div class="top"><span class="fl time">2016年11月6日 23:49</span><span class="fr btn foldbtn"></span></div>
                            <p>
                                {{ message.message }}
                            </p>
                        </div>
                    </div>

                    {% endfor %}

			</div>


			<div class="pageturn pagerright">
                <ul class="pagelist">





                            <li class="active"><a href="?page=1">1</a></li>





            </ul>
            </div>
		</div>

	</div>
{% endblock %}